# Generated by Django 4.2.30 on 2026-05-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_destacado_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar para mostrar en la sección de destacados del home'),
        ),
    ]
