# Generated by Django 5.2.14 on 2026-06-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rediseno_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contador de órdenes',
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='correlativo',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
